name: Fetch Data from GCS and Update GitHub Repository

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update_repo_with_gcs_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Google Cloud Storage library
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      - name: Configure Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-key.json"
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Download data from GCS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-key.json"
          BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
          OBJECT_KEY: ${{ secrets.GCP_OBJECT_KEY }}
        run: |
          python - <<EOF
          import os
          from google.cloud import storage

          # Initialize Google Cloud Storage client
          client = storage.Client()
          bucket = client.bucket(os.getenv("BUCKET_NAME"))
          blob = bucket.blob(os.getenv("OBJECT_KEY"))

          # Download the file
          file_name = os.path.basename(os.getenv("OBJECT_KEY"))
          blob.download_to_filename(file_name)
          print(f"Downloaded {file_name} from GCS.")
          EOF

      - name: Commit and push changes to repository
        env:
          FILE_NAME: ${{ secrets.GCP_OBJECT_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add the downloaded file to the repository
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          mv $(basename $FILE_NAME) path/in/repo/$(basename $FILE_NAME)  # Adjust path as needed
          git add path/in/repo/$(basename $FILE_NAME)
          git commit -m "Update data file from GCS"
          git push
