name: Upload Files to GCS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  upload_to_gcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Google Cloud Storage library
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      - name: Configure Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-key.json"
        run: |
          echo "${{ secrets.GCP_CREDENTIALS }}" > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Upload files to GCS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp-key.json"
          BUCKET_NAME: ${{ secrets.GCP_BUCKET_NAME }}
        run: |
          python - <<EOF
          import os
          from google.cloud import storage

          # Initialize Google Cloud Storage client
          client = storage.Client()
          bucket_name = os.getenv("BUCKET_NAME")
          bucket = client.bucket(bucket_name)

          # List of files to upload
          files_to_upload = [
              "path/to/your-file-1.parquet",
              "path/to/your-file-2.csv"  # Add more files as needed
          ]

          # Upload each file
          for file_path in files_to_upload:
              blob = bucket.blob(file_path)
              blob.upload_from_filename(file_path)
              print(f"Uploaded {file_path} to gs://{bucket_name}/{file_path}")
          EOF
